services:
  - type: web
    name: greenwatt-intake-clean
    runtime: python
    plan: starter
    buildCommand: |
      apt-get update && apt-get install -y poppler-utils
      pip install --upgrade pip
      pip install -r requirements.txt
      python install_signature_fonts.py
    startCommand: |
      # Use single worker and enable memory monitoring
      gunicorn app:app         --bind 0.0.0.0:$PORT         --workers 1         --worker-class sync         --timeout 120         --max-requests 50         --max-requests-jitter 10         --preload
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: MALLOC_TRIM_THRESHOLD_
        value: "0"
      - key: MALLOC_MMAP_THRESHOLD_
        value: "16384"
      - key: GUNICORN_CMD_ARGS
        value: "--max-requests=50 --max-requests-jitter=10"
